#!/bin/bash

mkdir -p build

gcc -c binarytree/enum.h -o build/enum.h.o
gcc -c binarytree/Tree.c -o build/Tree.o
flex -o build/lex.yy.c parser/prelexer.l
bison -d -o build/preparser.tab.c parser/preparser.y
gcc build/preparser.tab.c build/lex.yy.c build/Tree.o